\documentclass[11pt, oneside]{article}    
\usepackage{geometry}    
\title{Draw Color Chromatin}
\author{Ricky Lim}

\begin{document}
\maketitle
\section{Goal}
- Draw five color chromatin states (Filion, et al., 2010) on Drosophila Genome

\section{Load Dataset}
\subsection{Get Chromatin States}
<<dataset_state,cache=TRUE>>=
library(rtracklayer) #to import bed file into gRanges
parent_dir = "/Users/RickyLim/Dropbox/BlackChromatin_project/"
setwd(parent_dir)
print(getwd())
kc_state <- import("RawDataSets/GSE22069_Drosophila_chromatin_domains.bed")
colnames(kc_state) <- "State"
kc_state <- as(kc_state, "GRanges")
print(kc_state)
@

\subsection{Get States on the Drosophila Genome}
<<dros_genome, cache=TRUE>>=
library(BSgenome.Dmelanogaster.UCSC.dm3) #get the seq.length of dros.Genome
chr.len = seqlengths(Dmelanogaster)
#exclude chromosomes with suffix "_" , "M", "Het", "extra".
chr.len = chr.len[grep("_|M|U|Het|extra", names(chr.len), invert = T)] 
#order the chromosomes
kc_state= keepSeqlevels(kc_state, names(chr.len))   
seqlevels(kc_state) = names(chr.len) 
seqlengths(kc_state) = (chr.len)
print(kc_state)
@

\section{Let's Draw it}
<<draw_colorState, echo=TRUE, cache=TRUE>>=
library(ggbio) 
chrom.col <- c('black', 'blue', 'seagreen3', 'red', 'gold2')
black.col <- c('black', 'white', 'white', 'white', 'white')
p <- autoplot(kc_state, layout = "karyogram", aes(fill = State))
p + scale_fill_manual(values = black.col) + opts(legend.position = "none") 
p + scale_fill_manual(values = chrom.col) + opts(legend.position = "none") 
@

\section{MetaInfo}
<<echo=FALSE>>=
toLatex(sessionInfo())
@
\begin{itemize}\raggedright
  \item R version 2.15.1 (2012-06-22), \verb|x86_64-apple-darwin9.8.0|
  \item Locale: \verb|en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8|
  \item Base packages: base, datasets, graphics, grDevices, methods,
    stats, utils
  \item Other packages: BiocGenerics~0.4.0, Biostrings~2.26.3,
    BSgenome~1.26.1, BSgenome.Dmelanogaster.UCSC.dm3~1.3.19,
    GenomicRanges~1.10.6, ggbio~1.6.6, ggplot2~0.9.3, IRanges~1.16.6,
    rtracklayer~1.18.2
  \item Loaded via a namespace (and not attached):
    AnnotationDbi~1.20.3, Biobase~2.18.0, biomaRt~2.14.0,
    biovizBase~1.6.2, bitops~1.0-4.2, cluster~1.14.3, colorspace~1.2-1,
    DBI~0.2-5, dichromat~2.0-0, digest~0.6.3, evaluate~0.4.3,
    formatR~0.7, GenomicFeatures~1.10.1, grid~2.15.1, gridExtra~0.9.1,
    gtable~0.1.2, Hmisc~3.10-1, knitr~1.1, labeling~0.1,
    lattice~0.20-13, MASS~7.3-23, munsell~0.4, parallel~2.15.1,
    plyr~1.8, proto~0.3-10, RColorBrewer~1.0-5, RCurl~1.95-3,
    reshape2~1.2.2, Rsamtools~1.10.2, RSQLite~0.11.2, scales~0.2.3,
    stats4~2.15.1, stringr~0.6.2, tools~2.15.1,
    VariantAnnotation~1.4.9, XML~3.95-0.1, zlibbioc~1.4.0
\end{itemize}
\end{document}